### ISSUE TITLE
Rename style file extension to .user.css to get recognized as style 

### ISSUE THREAD

**Issue by tobimori** [losuler/hacker-news-userstyle#1]
Rename style file extension to .user.css to get recognized as style. The raw link will then automatically open an install window in Stylus.

**Comment by losuler** [comment]
Thanks, I didn't realise this! I also added a simple userstyle header so that Stylus opens the file correctly.

I saw your [awesome-userstyles](https://github.com/tobimori/awesome-userstyles) repo too, nice work :) A curated repo of userstyles is much nicer than https://userstyles.org, which is so terrible to use.
